PurchaseOrderReceivings/Controllers/ReceivingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PurchaseOrderReceivings.Models.ViewModel;
using PurchaseOrderReceivings.Models.EntityManager;

namespace PurchaseOrderReceivings.Controllers
{
    public class ReceivingsController : Controller
    {
        // GET: Receivings
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Receivings()
        {
            ProductManager PM = new ProductManager();

            ProductReceiveView PRV = new ProductReceiveView
            {
                ProductManifestList = PM.GetManifestProducts("")
            };


            return View(PRV.ProductManifestList);
        }

        [HttpPost]
        public ActionResult Receivings(ProductManifests manifest)
        {
            ProductManager PM = new ProductManager();

            ProductReceiveView PRV = new ProductReceiveView
            {
                ProductManifestList = PM.GetManifestProducts(manifest.Manifest_Number)
            };

            ViewBag.Message = "Your Product Receiving History page.";

            return View(PRV.ProductManifestList);
        }


        public ActionResult DownloadPO(ProductManifests manifest)
        {          
            ProductManager PM = new ProductManager();

            PurchaseOrder PO = PM.GetPurchaseOrder(manifest.Manifest_Number);

            if (PO != null)
            {
                string dPath = PO.Purchase_Order_Document_Path;
                return File(dPath, "application/pdf");
            }
            else
            {
                string fileName = "NoOrderDocumentFound.pdf";
                string path = System.IO.Path.Combine(@"G:/Suppy Chain/PurchaseOrders/", fileName);
                return File(path, "application/pdf");
            }                         
        }
    }
}

PurchaseOrderReceivings/Views/Receivings/Receivings.cshtml
@model List<PurchaseOrderReceivings.Models.ViewModel.ProductManifests>
<br />
@{
    ViewBag.Title = "Product History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />

<!DOCTYPE html>
@using (Html.BeginForm())
{
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title></title>
    </head>


    <body>
        <br />
        @*<div class="form-horizontal">*@
            <div class="jumbotron">
                <h4>Search Product Receiving Manifests</h4>
                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(Model => Model.FirstOrDefault().Manifest_Number, htmlAttributes: new { @class = "control-label col-sm-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(Model => Model.FirstOrDefault().Manifest_Number, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(Model => Model.FirstOrDefault().Manifest_Number, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Search" class="btn btn-default" />
                        @*@(Url.Action("Product", "Home", new { product = Model.Product_Code }))*@
                    </div>

                    <br />
                     
                    <p><a class="btn btn-primary btn-lg" href="@Url.Action("DownloadPO", "Receivings", Model.FirstOrDefault())" target="_blank">P. O. LookUp &raquo;</a></p>
            

                        @*@Html.LabelFor(Model => Model.FirstOrDefault().Product_Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(Model => Model.FirstOrDefault().Product_Description, new { htmlAttributes = new { @class = "form-control" } })
                        </div>*@
                </div>

                    @*<div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Search" class="btn btn-default" />
                        </div>
                    </div>*@
            </div>

            <div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Description</th>
                            <th>Received Date</th>
                            <th>Received Qnty</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var ph in Model)
                        {
                            <tr>
                                <td> @Html.DisplayFor(m => ph.Product_Code)</td>
                                <td> @Html.DisplayFor(m => ph.Product_Description)</td>
                                <td> @Html.DisplayFor(m => ph.WH_Receipt_Date)</td>
                                <td> @Html.DisplayFor(m => ph.Received_Quantity)</td>
                            </tr>
                        }
                    </tbody>
                </table>


            </div>

            <div>
                @Html.ActionLink("Back to Home", "Index", "Home")
            </div>
    </body>
</html>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}